label = int / text
values = any

COSE_Key = {
    &(kty: 1) => text / int
    ? &(kid: 2) => bytes
    ? &(alg: 3) => text / int
    ? &(key_ops: 4) => [+ (text / int) ]
    ? &(base_iv: 5) => bytes
    * label => values
}
